In [7]:
from modules.data_loader import DataLoaderFDATA

In [8]:
loader = DataLoaderFDATA("datasets/fdata/22_04_full.parquet")

In [9]:
df = loader.load_preprocessed_data()
df.head()

,Job Number,Submit Time,Wait Time,Run Time,Requested Number of Nodes,Requested Time,User ID,Group ID,Requested Number of CPU,Requested Number of GPU,Total Requested Memory,Desired QoS
338053,8688434,0,17,1,10,60,286,0,480,-1,30408704,127
338054,8688436,1488,13,9,1,3600,1379,0,48,-1,89063424,127
338055,8688437,1579,11,3,1,3600,1379,0,48,-1,85721088,127
334545,8684823,1633,22,3,1,3600,1379,0,48,-1,88014848,127
334546,8684824,2304,13,1,10,60,286,0,480,-1,32309248,127

In [10]:
df = loader.extract_additional_features()
df.head()

,Job Number,Submit Time,Wait Time,Run Time,Requested Number of Nodes,Requested Time,User ID,Group ID,Requested Number of CPU,Requested Number of GPU,...,Prev Duration (NH4) 3,Avg Duration (NH4) 2,Avg Duration (NH4) 3,Avg Duration (NH4) All,Prev Requested Nodes 1,Prev Requested Nodes 2,Prev Requested Nodes 3,Avg Requested Nodes 2,Avg Requested Nodes 3,Avg Requested Nodes All
28236,8442538,169671,18183,16481,6144,18000,5,0,294912,-1,...,0.0,0.0,0.000000,3.00,0.0,0.0,0.0,0.0,0.0,6144.0
26891,8441019,169899,35,16170,768,18000,5,0,36864,-1,...,0.0,1.5,1.000000,3.00,6144.0,0.0,0.0,3072.0,2048.0,3456.0
27154,8441296,170206,1454,16412,2592,18000,5,0,124416,-1,...,0.0,3.0,2.000000,3.00,768.0,6144.0,0.0,3456.0,2304.0,3168.0
30088,8444655,171039,815,54740,768,86400,5,0,36864,-1,...,3.0,3.0,3.000000,3.25,2592.0,768.0,6144.0,1680.0,3168.0,2568.0
30491,8445126,171143,5373,54968,2592,86400,5,0,124416,-1,...,3.0,3.5,3.333333,3.40,768.0,2592.0,768.0,1680.0,1376.0,2572.8

In [11]:
train_df, test_df = loader.split_train_test()

In [12]:
df.shape

(424381, 40)

In [13]:
train_df.shape

(339504, 40)

In [14]:
test_df.shape

(84877, 40)

In [15]:
loader.save_parquet("22_04")

Files saved in: C:\Users\trap9\Documents\Università\Dottorato\Notebooks\Runtime_Prediction\datasets\fdata

In [16]:
import pandas as pd

In [17]:
df_full = pd.read_parquet("datasets/fdata/22_04_full.parquet", engine="pyarrow").copy()
df_full.head()

,Job Number,User ID,Requested Number of Nodes,Requested Number of CPU,Requested Number of GPU,Total Requested Memory,Desired QoS,Requested Time,Run Time,Duration (H4),...,Avg Duration (NH7) 2,Avg Duration (NH7) 3,Avg Duration (NH7) All,Prev Requested Nodes 1,Prev Requested Nodes 2,Prev Requested Nodes 3,Avg Requested Nodes 2,Avg Requested Nodes 3,Avg Requested Nodes All,Submit Time
28236,8442538,5,6144,294912,-1,26985234432,127,18000,16481,Medium,...,0.0,0.000000,5.00,0.0,0.0,0.0,0.0,0.0,6144.0,169671
26891,8441019,5,768,36864,-1,27232960512,127,18000,16170,Medium,...,2.5,1.666667,5.00,6144.0,0.0,0.0,3072.0,2048.0,3456.0,169899
27154,8441296,5,2592,124416,-1,27018002432,127,18000,16412,Medium,...,5.0,3.333333,5.00,768.0,6144.0,0.0,3456.0,2304.0,3168.0,170206
30088,8444655,5,768,36864,-1,26390233088,127,86400,54740,Long,...,5.0,5.000000,5.25,2592.0,768.0,6144.0,1680.0,3168.0,2568.0,171039
30491,8445126,5,2592,124416,-1,26468220928,127,86400,54968,Long,...,5.5,5.333333,5.40,768.0,2592.0,768.0,1680.0,1376.0,2572.8,171143

In [18]:
df_full.columns

Index(['Job Number', 'User ID', 'Requested Number of Nodes',
       'Requested Number of CPU', 'Requested Number of GPU',
       'Total Requested Memory', 'Desired QoS', 'Requested Time', 'Run Time',
       'Duration (H4)', 'Duration (H7)', 'Prev Run Time 1', 'Prev Run Time 2',
       'Prev Run Time 3', 'Avg Run Time 2', 'Avg Run Time 3',
       'Avg Run Time All', 'Prev Duration (NH4) 1', 'Prev Duration (NH4) 2',
       'Prev Duration (NH4) 3', 'Avg Duration (NH4) 2', 'Avg Duration (NH4) 3',
       'Avg Duration (NH4) All', 'Prev Duration (NH7) 1',
       'Prev Duration (NH7) 2', 'Prev Duration (NH7) 3',
       'Avg Duration (NH7) 2', 'Avg Duration (NH7) 3',
       'Avg Duration (NH7) All', 'Prev Requested Nodes 1',
       'Prev Requested Nodes 2', 'Prev Requested Nodes 3',
       'Avg Requested Nodes 2', 'Avg Requested Nodes 3',
       'Avg Requested Nodes All', 'Submit Time'],
      dtype='object')

In [19]:
df_train = pd.read_parquet("datasets/fdata/22_04_train.parquet", engine="pyarrow").copy()
df_train.head()

,Job Number,User ID,Requested Number of Nodes,Requested Number of CPU,Requested Number of GPU,Total Requested Memory,Desired QoS,Requested Time,Run Time,Duration (H4),...,Avg Duration (NH7) 2,Avg Duration (NH7) 3,Avg Duration (NH7) All,Prev Requested Nodes 1,Prev Requested Nodes 2,Prev Requested Nodes 3,Avg Requested Nodes 2,Avg Requested Nodes 3,Avg Requested Nodes All,Submit Time
338053,8688434,286,10,480,-1,30408704,127,60,1,Very-Short,...,0.0,0.000000,1.0,0.0,0.0,0.0,0.0,0.000000,10.0,0
338054,8688436,1379,1,48,-1,89063424,127,3600,9,Very-Short,...,0.0,0.000000,1.0,0.0,0.0,0.0,0.0,0.000000,1.0,1488
338055,8688437,1379,1,48,-1,85721088,127,3600,3,Very-Short,...,0.5,0.333333,1.0,1.0,0.0,0.0,0.5,0.333333,1.0,1579
334545,8684823,1379,1,48,-1,88014848,127,3600,3,Very-Short,...,1.0,0.666667,1.0,1.0,1.0,0.0,1.0,0.666667,1.0,1633
334546,8684824,286,10,480,-1,32309248,127,60,1,Very-Short,...,0.5,0.333333,1.0,10.0,0.0,0.0,5.0,3.333333,10.0,2304

In [20]:
df_test = pd.read_parquet("datasets/fdata/22_04_test.parquet", engine="pyarrow").copy()
df_test.head()

,Job Number,User ID,Requested Number of Nodes,Requested Number of CPU,Requested Number of GPU,Total Requested Memory,Desired QoS,Requested Time,Run Time,Duration (H4),...,Avg Duration (NH7) 2,Avg Duration (NH7) 3,Avg Duration (NH7) All,Prev Requested Nodes 1,Prev Requested Nodes 2,Prev Requested Nodes 3,Avg Requested Nodes 2,Avg Requested Nodes 3,Avg Requested Nodes All,Submit Time
336833,8687223,1122,82,3936,-1,573046784,127,2400,462,Short,...,1.5,1.333333,1.508870,6.0,82.0,6.0,44.0,31.333333,8.889789,1894043
422694,8773168,299,128,6144,-1,230293504,127,3600,716,Short,...,3.0,3.000000,2.463987,128.0,128.0,128.0,128.0,128.000000,104.140017,1894044
338289,8688742,299,128,6144,-1,233439232,127,3600,1063,Short,...,3.0,3.000000,2.464296,128.0,128.0,128.0,128.0,128.000000,104.153758,1894044
422695,8773169,299,128,6144,-1,228720640,127,3600,721,Short,...,3.0,3.000000,2.464065,128.0,128.0,128.0,128.0,128.000000,104.143454,1894044
422685,8773159,299,128,6144,-1,228130816,127,3600,686,Short,...,3.0,3.000000,2.464219,128.0,128.0,128.0,128.0,128.000000,104.150324,1894044